### ISSUE TITLE
Throw an error if source of layer doesn't exist

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/carto.js#1379]
Somehow related to https://github.com/CartoDB/cartodb/issues/9179.

We should check if an analysis source exists before assigning a new source to a layer or datasource.

eg:

```
layer.set('source', 'b3'); // throws an error if cdb.js doesn't know about 'b3'
```

cc: @xavijam @viddo

**Comment by viddo** [comment]
Sounds like a programmer error, for which I'd prefer the code to yell back at me rather than silently doing nothing. Where/why would we try to set a source that doesn't exist? I think it would make more sense to check the existence of the node before changing the source of the layer in that case, and provide a more actionable error, e.g.:

```js
// somewhere…
if (!sourceExists(nodeId)) throw new Error('node ' + nodeId + ' not found, make sure it exists before assigning it as a source to layer');

layer.set('source', nodeId);
```

**Comment by alonsogarciapablo** [comment]
> Where/why would we try to set a source that doesn't exist?

I described a case where this happened in https://github.com/CartoDB/cartodb/issues/9179#issuecomment-236581024.

My idea is to throw an error like the one you are suggesting to inform the Builder that the there's  something wrong and the source it's trying to set is not right... Of course the Builder would need to handle this error elegantly... Makes sense?

**Comment by viddo** [comment]
I missed that comment, sorry.
Then yes, this sounds very reasonable. 👍
