### ISSUE TITLE
We should trigger a filters change when a filter is modified within a widget

### ISSUE THREAD

**Issue by xavijam** [CartoDB/carto.js#1611]
We have discovered we are listening any change over a widget for changing the state in Deep-insights [link](https://github.com/CartoDB/deep-insights.js/blob/master/src/api/dashboard.js#L70). That's not optimal in any side, so a good way to fix it would be to just trigger a `change:filters` event when a user has filtered the widget.

How does it sound @alonsogarciapablo?

**Comment by alonsogarciapablo** [comment]
We could even abstract it a bit more so that we don't need to know about filters specifically. A widget model know about it's state, so they can just trigger a `change:state` event when something related to it's state changes:

```
widgetModel.on('change:state', function () {
  var widgetState = widgetModel.getState();
  // do something with widgetState
});
```

Also, since we want to be notified about changes on any of the existing widgets, we could have method at the `.widgets` level:

```
this._dashboard.widgets.on('change:state, function (widgetModel) {
  var widgetState = widgetModel.getState();
  // do something with the state
});
```

**Comment by xavijam** [comment]
Even better 👏 .
