### ISSUE TITLE
Browsers support

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#1994]
As suggested by a customer in https://carto.com/documentation/cartojs/support/browsers/ we should state that `carto.js` it's suitable for mobile browsers as well.

Previous to that we need to check that they work, of course.

Adding to this issue:
- We need to add a row to https://carto.com/developers/carto-js/support/browser-support/ for most used mobile browsers (as Iago says below).
- Modify the desktop table to say `Edge` instead of `IE`, add an entry for IE11 and rewrite the first sentence as `CARTO.js works for the last 2 versions in any modern browser and IE11`

**Comment by ivanmalagon** [comment]
Waiting for customer's feedback.

**Comment by IagoLast** [comment]
I started to play with https://testobject.com to test [this map](https://team.carto.com/u/iago-carto/builder/a025e883-f78a-4401-9450-d33ae0bfc93d/embed) in order to do some real device testing.

- iPhone 5: IOS 10.0.2
![iphone 5 free - ios 10 0 2](https://user-images.githubusercontent.com/2657897/34952586-858a7b62-fa1a-11e7-9119-d4ac7628014c.png)

- Motorola MotoE: Android 6.0, Chrome 63.0.3239.111
![2018-01-15 16_27_29 - motorola moto e 2nd gen - android 6 0](https://user-images.githubusercontent.com/2657897/34952619-a0352e26-fa1a-11e7-9d89-7016de724557.png)

**Comment by IagoLast** [comment]
Regarding to this issue I see the following steps:

1. Write a list with the most used mobile browsers (maybe from [here](http://gs.statcounter.com/browser-version-market-share#monthly-201701-201712-bar)?
2. Decide the supported mobile browsers
3. Manually test those browsers
4. Update docs according to this process

**Comment by ivanmalagon** [comment]
Is it possible to test interaction? (The problem reported by the customer that triggered this issue)

**Comment by IagoLast** [comment]
> Is it possible to test interaction

yep, both devices had popups working :D

**Comment by jesusbotella** [comment]
I think we can use most of the ones that CanIUse have in their page: iOS Safari, Chrome for Android, and Samsung Internet. And maybe Opera Mini and UC Browser for Android, but I don't know if would put that ones.

**Comment by rubenmoya** [comment]
Would you add Firefox for Android?

**Comment by rubenmoya** [comment]
Mobile browsers usage in the last year:

![screen shot 2018-07-11 at 09 35 01](https://user-images.githubusercontent.com/905225/42557073-c32dbf7a-84ed-11e8-8c2b-ae5de2ccecf5.png)

**Comment by ivanmalagon** [comment]
Let's check it in
- Chrome
- Safari
- Android browser
- UC Browser

**Comment by IagoLast** [comment]
mobile only?

**Comment by ivanmalagon** [comment]
This issue is about mobile, yes.

**Comment by jesusbotella** [comment]
I have checked the examples in Chrome for Android, iOS Safari, and Android browser and work flawlessly.

In Android Browser, CARTO.js itself works but the examples are not being shown properly due to the ES6 code in the examples. I don't know if we want to fix that 🤷‍♂️.

I'll test UC Browser at home with an Android phone capable of supporting it.

**Comment by ivanmalagon** [comment]
These are the main browsers in our GA for embeds. I think we're good to extrapolate that this is a very representative image of our users.

Let's take care of these ones.

![image](https://user-images.githubusercontent.com/1078228/42625561-57584208-85c8-11e8-8eb1-96d823da75db.png)

**Comment by ivanmalagon** [comment]
This was done at https://github.com/CartoDB/carto.js/issues/2168
