### ISSUE TITLE
Parsing error in torque-layer having apostrophes inside a field

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto.js#2131]
### Context & Steps to Reproduce
See this Builder issue: https://github.com/CartoDB/cartodb/issues/13976

### Additional info
There is a WIP regarding to 'style form' at https://github.com/CartoDB/cartodb/pull/14017 but the error remains despite of changing the UI

**Comment by jesusbotella** [comment]
I am having a hard time debugging this issue 😂. I have tried all the thing that I could come up with until now.

So the thing is that we're sending a query like this one, where you can see that the values in single quotes are not escaped:
```sql
select *, (CASE WHEN \"name\" = '' THEN 1 WHEN \"name\" = 'Perfect room in Madrid's Center' THEN 2 WHEN \"name\" = 'Beautiful and bright room in Callao' THEN 3 WHEN \"name\" = 'Cozy room in city center' THEN 4 WHEN \"name\" = 'Apartamento en el centro de Madrid' THEN 5 WHEN \"name\" = 'Beautiful room in Madrid's center' THEN 6 WHEN \"name\" = 'Cozy room' THEN 7 WHEN \"name\" = 'Habitación en el centro de Madrid' THEN 8 WHEN \"name\" = 'Habitación privada' THEN 9 WHEN \"name\" = 'Madrid Center: Puerta del Sol, Tirso de Molina' THEN 10  ELSE 11  END) as value FROM (<%= sql %>) __wrapped
```

I tried to escape the single quotes that wrap the string value but it is nearly impossible because JSON.stringify removes them or escape them twice.

So I've tried different strategies:

**1. Change the quotes that wrap the string value to double quotes**
The query we send in this case is: 
```sql
select *, (CASE WHEN \"name\" = \"\" THEN 1 WHEN \"name\" = \"Perfect room in Madrid's Center\" THEN 2 WHEN \"name\" = \"Beautiful and bright room in Callao\" THEN 3 WHEN \"name\" = \"Cozy room in city center\" THEN 4 WHEN \"name\" = \"Apartamento en el centro de Madrid\" THEN 5 WHEN \"name\" = \"Beautiful room in Madrid's center\" THEN 6 WHEN \"name\" = \"Cozy room\" THEN 7 WHEN \"name\" = \"Habitación en el centro de Madrid\" THEN 8 WHEN \"name\" = \"Habitación privada\" THEN 9 WHEN \"name\" = \"Madrid Center: Puerta del Sol, Tirso de Molina\" THEN 10  ELSE 11  END) as value FROM (<%= sql %>) __wrapped
```

The error that Windshaft returns is: `"TorqueRenderer: zero-length delimited identifier at or near """""`

**2. Dollar-quoted String Constants**
The query we send in this case is:
```sql
select *, (CASE WHEN \"name\" = '' THEN 1 WHEN \"name\" = $$Perfect room in Madrid's Center$$ THEN 2 WHEN \"name\" = $$Beautiful and bright room in Callao$$ THEN 3 WHEN \"name\" = $$Cozy room in city center$$ THEN 4 WHEN \"name\" = $$Apartamento en el centro de Madrid$$ THEN 5 WHEN \"name\" = $$Beautiful room in Madrid's center$$ THEN 6 WHEN \"name\" = $$Cozy room$$ THEN 7 WHEN \"name\" = $$Habitación en el centro de Madrid$$ THEN 8 WHEN \"name\" = $$Habitación privada$$ THEN 9 WHEN \"name\" = $$Madrid Center: Puerta del Sol, Tirso de Molina$$ THEN 10  ELSE 11  END) as value FROM (<%= sql %>) __wrapped
```
I had to set single quotes in the first CASE clause to avoid a worse error.
In this case the error that I received is: `"TorqueRenderer: syntax error at or near "$""`.

I don't know if I'm missing something but I am stuck with this.

Maybe @enekid can help!

**Comment by enekid** [comment]
@jesusbotella Take a look at https://github.com/CartoDB/cartodb/issues/13976#issuecomment-398103662

**Comment by jesusbotella** [comment]
It works!
I am gonna close this issue because it is not related to Carto.JS but to Builder instead, as the query is built in Builder.
