### ISSUE TITLE
Unexpected behaviors in legends 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/carto.js#2146]
While doing an acceptance of [this PR](https://github.com/CartoDB/carto.js/pull/2143), I found some unexpected behaviors in the legends. 

### Overlapping values

If you start playing with the max and min values of the point size, some of those values in the legend start overlapping each other. Look at the 42 below the 8.

<img width="522" alt="screen shot 2018-06-18 at 15 38 09" src="https://user-images.githubusercontent.com/16247628/41545267-20956d00-731b-11e8-8840-7101d189b8c3.png">

Or whatever is below the 75 in this case.

<img width="527" alt="screen shot 2018-06-18 at 15 38 38" src="https://user-images.githubusercontent.com/16247628/41545291-29b34812-731b-11e8-8149-79a21a8f416c.png">

I'm not sure if this edge case was contemplated in the original design, though. Do you guys know? @urbanphes @piensaenpixel 

### Two buckets scenario

When I select two buckets, the representation in the legend makes it look like if there was only one circle, so one size. There should be two. 

<img width="527" alt="2 buckets" src="https://user-images.githubusercontent.com/16247628/41545603-d6a78dda-731b-11e8-8058-1dea3299305f.png">

### Input values get changed automatically

![legends2](https://user-images.githubusercontent.com/16247628/41545495-95f9a746-731b-11e8-844c-5648bd6d9444.gif)

Granted, who would want to set both the Min and Max to be 45? But if we allow it, we should support it. If not, we should either not allow it or add a tooltip/warning message that says that the Min value should be lower than the Max...  

### Jenks are breaking the legends 

When I switched to Jenks in the style tab, this happened

<img width="707" alt="screen shot 2018-06-18 at 15 43 00" src="https://user-images.githubusercontent.com/16247628/41545735-2c2ec606-731c-11e8-8a60-8e5950cf0c63.png">

All the others worked fine. 

### Responsive behavior 

Look at what happens with the legends's box height when I resize the browser window...

![legends](https://user-images.githubusercontent.com/16247628/41545783-44c4d746-731c-11e8-9476-772d06e90bee.gif)

cc @ramiroaznar @jesusbotella

**Comment by ramiroaznar** [comment]
Related to https://github.com/CartoDB/cartodb/issues/14075

**Comment by jesusbotella** [comment]
Hey! I think we can break this issue in several ones.

I have been working in **Input values get changed automatically** and **Responsive behavior**, these are now done. I'm awaiting for Code Review, and then I'll tell you when acceptance is needed.

**Two buckets scenario** is being handled in https://github.com/CartoDB/cartodb/issues/14075. And **Jenks are breaking the legends** is working in production, so I think we can consider this a staging issue because of the limits.

So the only issue without handle is **Overlapping values**. What do you think if I open a new issue and take the discussion there? It is not going to be an easy thing to do.

**Comment by arianaescobar** [comment]
Sounds good :)

**Comment by ramiroaznar** [comment]
Dale candela.

**Comment by jesusbotella** [comment]
Deployed! 🚀

I don't know if I should add #2150 to RT kanban or not. Feel free to do it ;)
