### ISSUE TITLE
Possibility to have a version without Google Maps

### ISSUE THREAD

**Issue by cantacell** [CartoDB/carto.js#2188]
Is it possible to have a minified version without the code for Google Maps?
Or is it possible to compile without Google Maps?
Thanks

**Comment by jesusbotella** [comment]
👋 @cantacell!

The short answer is no, not easily.

We don't provide any custom versions without CARTO.js' Google Maps code.
Take into account that we don't bundle the whole Google Maps library but the needed code to make CARTO.js work with the library.

Unfortunately, there is no way for you to compile it without Google Maps with Webpack's Tree Shaking either because we don't use ES2015 module syntax and we would need to change the code to make it compatible.

So the only feasible way to do it is to make your own CARTO.js' fork and modify the code to remove it from the bundle and create your own CARTO.js' version.
